local anvil = require("anvil")

describe("Anvil command completion", function()
  it("includes new popup and command surfaces", function()
    local completions = anvil.complete("")

    assert.True(vim.tbl_contains(completions, "forge"))
    assert.True(vim.tbl_contains(completions, "run"))
    assert.True(vim.tbl_contains(completions, "blame"))
    assert.True(vim.tbl_contains(completions, "patch"))
    assert.True(vim.tbl_contains(completions, "notes"))
    assert.True(vim.tbl_contains(completions, "submodule"))
    assert.True(vim.tbl_contains(completions, "clone"))
    assert.True(vim.tbl_contains(completions, "file_dispatch"))
    assert.True(vim.tbl_contains(completions, "sparse_checkout"))
    assert.True(vim.tbl_contains(completions, "subtree"))
    assert.True(vim.tbl_contains(completions, "bundle"))
    assert.True(vim.tbl_contains(completions, "shortlog"))
    assert.True(vim.tbl_contains(completions, "repos"))
    assert.True(vim.tbl_contains(completions, "dispatch"))
    assert.True(vim.tbl_contains(completions, "mergetool"))
  end)

  it("filters new commands by prefix", function()
    assert.are.same({ "forge" }, anvil.complete("fo"))
    assert.are.same({ "run" }, anvil.complete("ru"))
    assert.are.same({ "blame" }, anvil.complete("bla"))
    assert.are.same({ "patch" }, anvil.complete("pa"))
    assert.are.same({ "notes" }, anvil.complete("no"))
    assert.are.same({ "submodule", "subtree" }, anvil.complete("sub"))
    assert.are.same({ "submodule" }, anvil.complete("subm"))
    assert.are.same({ "clone" }, anvil.complete("clo"))
    assert.are.same({ "file_dispatch" }, anvil.complete("file"))
    assert.are.same({ "sparse_checkout" }, anvil.complete("spa"))
    assert.are.same({ "subtree" }, anvil.complete("subt"))
    assert.are.same({ "bundle" }, anvil.complete("bun"))
    assert.are.same({ "shortlog" }, anvil.complete("sho"))
    assert.are.same({ "repos" }, anvil.complete("rep"))
    assert.are.same({ "dispatch" }, anvil.complete("dis"))
    assert.are.same({ "merge", "mergetool" }, anvil.complete("mer"))
    assert.are.same({ "mergetool" }, anvil.complete("merget"))
  end)
end)
