local neogit = require("neogit")

describe("Neogit command completion", function()
  it("includes new popup and command surfaces", function()
    local completions = neogit.complete("")

    assert.True(vim.tbl_contains(completions, "forge"))
    assert.True(vim.tbl_contains(completions, "run"))
    assert.True(vim.tbl_contains(completions, "blame"))
    assert.True(vim.tbl_contains(completions, "patch"))
    assert.True(vim.tbl_contains(completions, "notes"))
    assert.True(vim.tbl_contains(completions, "submodule"))
    assert.True(vim.tbl_contains(completions, "clone"))
    assert.True(vim.tbl_contains(completions, "file_dispatch"))
    assert.True(vim.tbl_contains(completions, "sparse_checkout"))
    assert.True(vim.tbl_contains(completions, "subtree"))
    assert.True(vim.tbl_contains(completions, "bundle"))
    assert.True(vim.tbl_contains(completions, "shortlog"))
    assert.True(vim.tbl_contains(completions, "repos"))
    assert.True(vim.tbl_contains(completions, "dispatch"))
    assert.True(vim.tbl_contains(completions, "mergetool"))
  end)

  it("filters new commands by prefix", function()
    assert.are.same({ "forge" }, neogit.complete("fo"))
    assert.are.same({ "run" }, neogit.complete("ru"))
    assert.are.same({ "blame" }, neogit.complete("bla"))
    assert.are.same({ "patch" }, neogit.complete("pa"))
    assert.are.same({ "notes" }, neogit.complete("no"))
    assert.are.same({ "submodule", "subtree" }, neogit.complete("sub"))
    assert.are.same({ "submodule" }, neogit.complete("subm"))
    assert.are.same({ "clone" }, neogit.complete("clo"))
    assert.are.same({ "file_dispatch" }, neogit.complete("file"))
    assert.are.same({ "sparse_checkout" }, neogit.complete("spa"))
    assert.are.same({ "subtree" }, neogit.complete("subt"))
    assert.are.same({ "bundle" }, neogit.complete("bun"))
    assert.are.same({ "shortlog" }, neogit.complete("sho"))
    assert.are.same({ "repos" }, neogit.complete("rep"))
    assert.are.same({ "dispatch" }, neogit.complete("dis"))
    assert.are.same({ "merge", "mergetool" }, neogit.complete("mer"))
    assert.are.same({ "mergetool" }, neogit.complete("merget"))
  end)
end)
